apiVersion: v1
kind: Service
metadata:
  name: hadoop-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8088
      name: hadoopport
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: terminalport
  selector:
    app: hadoop-app
